### ISSUE TITLE
Makefile error OS X 

### ISSUE THREAD

**Issue by LeahRoberts** [GregoryFaust/samblaster#14]
I'm getting an error when trying to install samblaster. Our IT specialist thinks it could be an OS X compatibility issue as I have an older version of OS X (10.6.8):

g++ -Wall -O3 -D BUILDNUM=21 -c samblaster.cpp -o samblaster.o
samblaster.cpp: In function ‘splitLine_t* readLine(FILE*)’:
samblaster.cpp:326: error: ‘getline’ was not declared in this scope
make: *** [samblaster.o] Error 1

Thanks in advance.

**Comment by GregoryFaust** [comment]
This appears to only occur in OSX installation prior to 10.7 due to the version of the GNU libraries installed. You could try to update to a newer version of the GNU libraries (perhaps dangerous). Alternatively, If I could tell at compile time if getline is or is not supported, then I could supply my own definition. But I don't want to slow down all other runtime configuration with my own potentially slower implementation of getline (The library routine has hopefully been (somewhat) optimized).

**Comment by LeahRoberts** [comment]
Thanks Greg,

I have updated my workspace to 10.10.3 (Yosemite) which seems to have fixed the problem. Thanks for getting back to me.
